### ISSUE TITLE
add stuff

### ISSUE THREAD

**Issue by theophinetheodore** [shibinbevin/shibinbevin.github.io#1]
add website url to about, maybe add a readme.md

lil tip: avoid using CDNs (not that they bad, but in case CDNs fail to load, you'll be stuck with the default font stack (no fontawesome, no google fonts) (same applies to anything loaded through a CDN)

**Comment by shibinbevin** [comment]
this will do for now, I'll work on the portfolio later

**Comment by theophinetheodore** [comment]
spoken like a true dev! (stackoverflow neckbeard, i mean)
